name: Generate PDF from Markdown
on:
  push:
    paths:
      - '*.md' # Trigger the workflow only when Markdown files are added or updated
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v4
    # Step 2: Install Pandoc and WeasyPrint
    - name: Install Pandoc and WeasyPrint
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc weasyprint
    # Step 3: Convert Markdown to HTML and then to PDF
    - name: Convert Markdown to PDF
      run: |
        for file in *.md; do
          [ -e "$file" ] || continue
          # Skip README.md
          if [ "$file" = "README.md" ]; then
            continue
          fi
          # Convert Markdown to HTML
          pandoc "$file" -o "${file%.md}.html"
          # Convert HTML to PDF using WeasyPrint
          weasyprint "${file%.md}.html" "${file%.md}.pdf"
        done
    # Step 4: Commit and Push PDFs Back to the Repository
    - name: Commit and push PDFs
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add *.pdf
        git commit -m "Add generated PDFs [skip ci]"
        git push
      env:
        # Pass the GitHub token to authenticate the push
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
